name: Sphinx build & deploy

on:
  push:

jobs:
  call_reusable_workflow:
    uses: vortexntnu/vortex-ci/.github/workflows/sphinx-build-and-deploy.yml@feat/sphinx
    permissions:
      pages: write
      id-token: write  # Explicitly granting required permission