name: Deploy Sphinx documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-docs:
    runs-on: ubuntu-22.04
    outputs: 
      docs_exists: ${{ steps.check.outputs.exists }}
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check if directory exists
      id: check
      run: |
        if [ -d "docs" ]; then
          echo "exists=true" >> $GITHUB_ENV
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_ENV
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

  build-deploy:
    needs: check-docs
    if: needs.check-docs.outputs.docs_exists == 'true'
    runs-on: ubuntu-22.04

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write      # to deploy to Pages
      id-token: write

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.7
      - run: pip install sphinx sphinx_rtd_theme myst_parser

      - name: Sphinx build
        run: |
          sphinx-build -b html ./docs/ _build


      - name: Upload static files as artifact
        id: upload
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: _build/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4